/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as TeamsIndexImport } from './routes/teams/index'
import { Route as TeamsCreateImport } from './routes/teams/create'
import { Route as TeamsLayoutImport } from './routes/teams/_layout'
import { Route as TeamsTeamidIndexImport } from './routes/teams/$team_id/index'
import { Route as TeamsTeamidAdminImport } from './routes/teams/$team_id/admin'
import { Route as TeamsTeamidElectionsCreateImport } from './routes/teams/$team_id/elections/create'
import { Route as TeamsTeamidElectionsElectionidImport } from './routes/teams/$team_id/elections/$election_id'
import { Route as TeamsTeamidMembersInviteInviteidImport } from './routes/teams/$team_id/members/invite/$invite_id'

// Create Virtual Routes

const TeamsImport = createFileRoute('/teams')()

// Create/Update Routes

const TeamsRoute = TeamsImport.update({
  path: '/teams',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TeamsIndexRoute = TeamsIndexImport.update({
  path: '/',
  getParentRoute: () => TeamsRoute,
} as any)

const TeamsCreateRoute = TeamsCreateImport.update({
  path: '/create',
  getParentRoute: () => TeamsRoute,
} as any)

const TeamsLayoutRoute = TeamsLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => TeamsRoute,
} as any)

const TeamsTeamidIndexRoute = TeamsTeamidIndexImport.update({
  path: '/$team_id/',
  getParentRoute: () => TeamsRoute,
} as any)

const TeamsTeamidAdminRoute = TeamsTeamidAdminImport.update({
  path: '/$team_id/admin',
  getParentRoute: () => TeamsRoute,
} as any)

const TeamsTeamidElectionsCreateRoute = TeamsTeamidElectionsCreateImport.update(
  {
    path: '/$team_id/elections/create',
    getParentRoute: () => TeamsRoute,
  } as any,
)

const TeamsTeamidElectionsElectionidRoute =
  TeamsTeamidElectionsElectionidImport.update({
    path: '/$team_id/elections/$election_id',
    getParentRoute: () => TeamsRoute,
  } as any)

const TeamsTeamidMembersInviteInviteidRoute =
  TeamsTeamidMembersInviteInviteidImport.update({
    path: '/$team_id/members/invite/$invite_id',
    getParentRoute: () => TeamsRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/teams': {
      preLoaderRoute: typeof TeamsImport
      parentRoute: typeof rootRoute
    }
    '/teams/_layout': {
      preLoaderRoute: typeof TeamsLayoutImport
      parentRoute: typeof TeamsRoute
    }
    '/teams/create': {
      preLoaderRoute: typeof TeamsCreateImport
      parentRoute: typeof TeamsImport
    }
    '/teams/': {
      preLoaderRoute: typeof TeamsIndexImport
      parentRoute: typeof TeamsImport
    }
    '/teams/$team_id/admin': {
      preLoaderRoute: typeof TeamsTeamidAdminImport
      parentRoute: typeof TeamsImport
    }
    '/teams/$team_id/': {
      preLoaderRoute: typeof TeamsTeamidIndexImport
      parentRoute: typeof TeamsImport
    }
    '/teams/$team_id/elections/$election_id': {
      preLoaderRoute: typeof TeamsTeamidElectionsElectionidImport
      parentRoute: typeof TeamsImport
    }
    '/teams/$team_id/elections/create': {
      preLoaderRoute: typeof TeamsTeamidElectionsCreateImport
      parentRoute: typeof TeamsImport
    }
    '/teams/$team_id/members/invite/$invite_id': {
      preLoaderRoute: typeof TeamsTeamidMembersInviteInviteidImport
      parentRoute: typeof TeamsImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  TeamsRoute.addChildren([
    TeamsCreateRoute,
    TeamsIndexRoute,
    TeamsTeamidAdminRoute,
    TeamsTeamidIndexRoute,
    TeamsTeamidElectionsElectionidRoute,
    TeamsTeamidElectionsCreateRoute,
    TeamsTeamidMembersInviteInviteidRoute,
  ]),
])

/* prettier-ignore-end */
