/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignInImport } from './routes/sign-in'
import { Route as TeamsImport } from './routes/_teams'
import { Route as IndexImport } from './routes/index'
import { Route as TeamsIndexImport } from './routes/teams/index'
import { Route as TeamsCreateImport } from './routes/teams/create'
import { Route as TeamsTeamidIndexImport } from './routes/teams/$team_id/index'
import { Route as TeamsTeamidAdminImport } from './routes/teams/$team_id/admin'
import { Route as TeamsTeamidElectionsCreateImport } from './routes/teams/$team_id/elections/create'
import { Route as TeamsTeamidElectionsElectionidImport } from './routes/teams/$team_id/elections/$election_id'
import { Route as TeamsTeamidMembersInviteInviteidImport } from './routes/teams/$team_id/members/invite/$invite_id'

// Create/Update Routes

const SignInRoute = SignInImport.update({
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const TeamsRoute = TeamsImport.update({
  id: '/_teams',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TeamsIndexRoute = TeamsIndexImport.update({
  path: '/teams/',
  getParentRoute: () => rootRoute,
} as any)

const TeamsCreateRoute = TeamsCreateImport.update({
  path: '/teams/create',
  getParentRoute: () => rootRoute,
} as any)

const TeamsTeamidIndexRoute = TeamsTeamidIndexImport.update({
  path: '/teams/$team_id/',
  getParentRoute: () => rootRoute,
} as any)

const TeamsTeamidAdminRoute = TeamsTeamidAdminImport.update({
  path: '/teams/$team_id/admin',
  getParentRoute: () => rootRoute,
} as any)

const TeamsTeamidElectionsCreateRoute = TeamsTeamidElectionsCreateImport.update(
  {
    path: '/teams/$team_id/elections/create',
    getParentRoute: () => rootRoute,
  } as any,
)

const TeamsTeamidElectionsElectionidRoute =
  TeamsTeamidElectionsElectionidImport.update({
    path: '/teams/$team_id/elections/$election_id',
    getParentRoute: () => rootRoute,
  } as any)

const TeamsTeamidMembersInviteInviteidRoute =
  TeamsTeamidMembersInviteInviteidImport.update({
    path: '/teams/$team_id/members/invite/$invite_id',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_teams': {
      preLoaderRoute: typeof TeamsImport
      parentRoute: typeof rootRoute
    }
    '/sign-in': {
      preLoaderRoute: typeof SignInImport
      parentRoute: typeof rootRoute
    }
    '/teams/create': {
      preLoaderRoute: typeof TeamsCreateImport
      parentRoute: typeof rootRoute
    }
    '/teams/': {
      preLoaderRoute: typeof TeamsIndexImport
      parentRoute: typeof rootRoute
    }
    '/teams/$team_id/admin': {
      preLoaderRoute: typeof TeamsTeamidAdminImport
      parentRoute: typeof rootRoute
    }
    '/teams/$team_id/': {
      preLoaderRoute: typeof TeamsTeamidIndexImport
      parentRoute: typeof rootRoute
    }
    '/teams/$team_id/elections/$election_id': {
      preLoaderRoute: typeof TeamsTeamidElectionsElectionidImport
      parentRoute: typeof rootRoute
    }
    '/teams/$team_id/elections/create': {
      preLoaderRoute: typeof TeamsTeamidElectionsCreateImport
      parentRoute: typeof rootRoute
    }
    '/teams/$team_id/members/invite/$invite_id': {
      preLoaderRoute: typeof TeamsTeamidMembersInviteInviteidImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  SignInRoute,
  TeamsCreateRoute,
  TeamsIndexRoute,
  TeamsTeamidAdminRoute,
  TeamsTeamidIndexRoute,
  TeamsTeamidElectionsElectionidRoute,
  TeamsTeamidElectionsCreateRoute,
  TeamsTeamidMembersInviteInviteidRoute,
])

/* prettier-ignore-end */
