networks:
  default:
    name: server
  services:
    name: services

services:
  server-setup:
    image: oven/bun:debian
    container_name: e-vote-api-setup
    working_dir: /usr/src/api
    volumes:
      - ./:/usr/src/api
    command: bun install

  prisma-setup:
    image: oven/bun:debian
    container_name: e-vote-prisma-setup
    working_dir: /usr/src/prisma
    depends_on:
      - server-setup
    volumes:
      - ./:/usr/src/prisma
    command: bunx prisma generate

  ballot-service:
    image: oven/bun:debian
    container_name: e-vote-ballot-service
    depends_on:
      - prisma-setup
    working_dir: /usr/src/api
    volumes:
      - ./:/usr/src/api
    networks:
      - services
    command: bun run --hot services/ballot-service/index.ts

  proposition-service:
    image: oven/bun:debian
    container_name: e-vote-proposition-service
    depends_on:
      - prisma-setup
    working_dir: /usr/src/api
    volumes:
      - ./:/usr/src/api
    networks:
      - services
    command: bun run --hot services/proposition-service/index.ts

  validation-service:
    image: oven/bun:debian
    container_name: e-vote-validation-service
    depends_on:
      - prisma-setup
    working_dir: /usr/src/api
    volumes:
      - ./:/usr/src/api
    networks:
      - services
    command: bun run --hot services/validation-service/index.ts

  server:
    image: oven/bun:debian
    container_name: e-vote-server
    depends_on:
      - prisma-setup
      - ballot-service
      - proposition-service
      - validation-service
    working_dir: /usr/src/api
    volumes:
      - ./:/usr/src/api
    ports:
      - 3000:3000
    networks:
      - services
      - default
    command: bun run --hot server/index.ts

  frontend-setup:
    image: oven/bun:debian
    container_name: e-vote-frontend-setup
    working_dir: /usr/src/app
    volumes:
      - ./server/frontend:/usr/src/app
    command: bun install

  frontend:
    image: oven/bun:debian
    container_name: e-vote-frontend
    depends_on:
      - frontend-setup
      - server
    working_dir: /usr/src/app
    volumes:
      - ./server/frontend:/usr/src/app
    ports:
      - 4000:4000
    networks:
      - default
    command: bun dev --host



