networks:
  default:
    name: server
  services:
    name: services

services:
  server-setup:
    image: oven/bun:debian
    container_name: e-vote-api-setup
    working_dir: /usr/src/api
    volumes:
      - ./:/usr/src/api
    command: bun install

  prisma-setup:
    image: oven/bun:debian
    container_name: e-vote-prisma-setup
    working_dir: /usr/src/prisma
    depends_on:
      - server-setup
    volumes:
      - ./:/usr/src/prisma
    environment:
      - DATABASE_URL=postgres://postgres:password@pg:5432/e-vote
    command: bunx prisma migrate deploy
