# Stage 1: Build the React application
# FROM node:20 AS builder
# ENV NODE_ENV=production
# WORKDIR /usr/srv/app
# COPY package*.json ./
# RUN yarn install --verbose
# COPY . .
# RUN yarn build --verbose

# # Stage 2: Serve the app on Nginx
# FROM nginx:stable-alpine
# COPY --from=builder /usr/srv/app/dist /usr/share/nginx/html
# CMD ["nginx", "-g", "daemon off;"]