services:
  api:
    image: node:lts-alpine
    environment:
      NODE_ENV: development
      PORT: 4000
      BALLOT_SERVICE_URL: http://ballot-service:4000
      PROPOSITION_SERVICE_URL: http://proposition-service:4000
      VALIDATION_SERVICE_URL: http://validation-service:4000
    volumes:
      - ./packages/backend/api:/api
      - ./packages/backend/prisma:/prisma
    working_dir: /api
    ports:
      - 4000:4000
      - 9230:9229
    command: /bin/sh -c "yarn install && yarn nodemon --signal SIGINT --inspect=0.0.0.0:9229 --nolazy src/index.ts"

  ballot-service:
    image: node:lts-alpine
    environment:
      NODE_ENV: development
      PORT: 4000
      PROOF_SECRET: YWE8LV72PXJUHDACF5MZGK
    volumes:
      - ./packages/backend/ballot-service:/api
      - ./packages/backend/prisma:/prisma
    working_dir: /api
    ports:
      - 9231:9229
    command: /bin/sh -c "yarn install && yarn nodemon --signal SIGINT --inspect=0.0.0.0:9229 --nolazy src/index.ts"

  proposition-service:
    image: node:lts-alpine
    environment:
      NODE_ENV: development
      PORT: 4000
      PROOF_SECRET: RHDZAP9WNFU8427EMSXJQL
    volumes:
      - ./packages/backend/proposition-service:/api
      - ./packages/backend/prisma:/prisma
    working_dir: /api
    ports:
      - 9232:9229
    command: /bin/sh -c "yarn install && yarn nodemon --signal SIGINT --inspect=0.0.0.0:9229 --nolazy src/index.ts"

  validation-service:
    image: node:lts-alpine
    environment:
      NODE_ENV: development
      PORT: 4000
      PROOF_SECRET: LPWBZH8XMTVDYEG2RASNK3
    volumes:
      - ./packages/backend/validation-service:/api
      - ./packages/backend/prisma:/prisma
    working_dir: /api
    ports:
      - 9233:9229
    command: /bin/sh -c "yarn install && yarn nodemon --signal SIGINT --inspect=0.0.0.0:9229 --nolazy src/index.ts"

  frontend:
    image: node:lts-alpine
    environment:
      NODE_ENV: development
      VITE_CLERK_PUBLISHABLE_KEY: pk_test_cmljaC1tYXJ0aW4tNzMuY2xlcmsuYWNjb3VudHMuZGV2JA
      VITE_API_BASE_URL: http://localhost:4000
    volumes:
      - ./packages/app:/app
    working_dir: /app
    ports:
      - 3000:3000
      - 3010:3010
    command: /bin/sh -c "yarn install && yarn dev --host"
