name: Build and Push Docker Images to Docker Hub

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build and push Frontend
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: ./packages/app
      #     push: true
      #     tags: kasperverner/e-vote-app:latest

      - name: Build and push API
        uses: docker/build-push-action@v5
        with:
          context: ./packages/backend
          file: api.dockerfile
          push: true
          tags: kasperverner/e-vote-api:latest

      - name: Build and push Ballot Service
        uses: docker/build-push-action@v5
        with:
          context: ./packages/backend
          file: ballot-service.dockerfile
          push: true
          tags: kasperverner/e-vote-ballot-service:latest

      - name: Build and push Propositotion Service
        uses: docker/build-push-action@v5
        with:
          context: ./packages/backend
          file: proposition-service.dockerfile
          push: true
          tags: kasperverner/e-vote-proposition-service:latest

      - name: Build and push Validation Service
        uses: docker/build-push-action@v5
        with:
          context: ./packages/backend
          file: validation-service.dockerfile
          push: true
          tags: kasperverner/e-vote-validation-service:latest
